name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read variables
        run: |
          stableVersion=$(grep "stableVersion:" .github/variables.yml | awk -F ": " '{print $2}')
          echo "stableVersion=$stableVersion" >> $GITHUB_ENV
          
      - name: Get Tags
        id: get_tags
        run: |
          tags=$(git ls-remote --tags origin | awk '{print $2}' | awk -F/ '{print $NF}')
          echo "::set-output name=tags::$tags"
          
      - name: Run build
        run: |
          echo "Running build task..."
          tags="${{ steps.get_tags.outputs.tags }}"
          existing_tag="${{ env.stableVersion }}"
          if [[ $tags =~ (^|[[:space:]])$existing_tag($|[[:space:]]) ]]; then
            echo "Tag $existing_tag exists! Failing the build."
            exit 1
          else
            echo "Tag $existing_tag does not exist. Build can continue."
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'

    steps:
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.stableVersion }}
          release_name: Release ${{ env.stableVersion }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - Third Change
          draft: false
          prerelease: false
          
          
          
